name: CI

on:
  push:
    branches: [ main ]
  # pull_request:
    # branches: [ main ]
  
  workflow_dispatch: # allows running manually

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Build and run tests
        run: |
          cd source
          dotnet test